 
version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "81:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        env_file: .env
        environment:
            - MYSQL_HOST=mysql
        volumes:
            - ./app:/app
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        env_file: .env
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
